global:
  resolve_timeout: 5m

route:
  receiver: webhook-internal
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: webhook-internal
    webhook_configs:
      - url: 'http://jumpcloud-api:8000/v1/alerts/webhook'
        send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity = critical
    target_matchers:
      - severity = warning
    equal: ['alertname']
